# This workflow gets the list of all changed .spec files,
# and triggers a rebuild on COPR for each of them via webhook.

name: Rebuild changed packages on COPR
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-rebuild-for-modified:
    name: Trigger rebuild for modified .spec files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get modified .spec files
        id: spec-modified
        uses: tj-actions/changed-files@v39
        with:
          files: specs/*.spec

      - name: Send rebuild request to COPR
        env:
          # URL: ${{ secrets.COPR_WEBHOOK_URL }}
          URL: https://example.org/id
        run: |
          for FILE in ${{ steps.spec-modified.outputs.modified_files }}; do
            echo "$FILE changed"
            echo "Webhook URL: $URL/$FILE"
          done
